# This file was generated by GoReleaser. DO NOT EDIT.
cask "kirocc" do
  name "kirocc"
  desc "Local proxy server that relays Anthropic Messages API requests to the Kiro backend"
  homepage "https://github.com/d-kuro/kirocc"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kirocc"

  on_macos do
    on_intel do
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_darwin_amd64.tar.gz"
      sha256 "3270d761e5edcb31d2c6e3ffd4a495091ae7986ee3d4a99e48baacda1eea3fd7"
    end
    on_arm do
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_darwin_arm64.tar.gz"
      sha256 "2c1a452db4fb75db05afffe25ceb879296f795e49a5a832bf836a6f2e69207ca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_linux_amd64.tar.gz"
      sha256 "1de1eabd2a4bee92874da34b415e9ae1af8792c65d67f8c6cfa43fea1e1e00aa"
    end
    on_arm do
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_linux_arm64.tar.gz"
      sha256 "6f34b2dac8ad40ab5a98cc95c2ddc7ec93cb65f82be04f1a453ad0e16652f65c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kirocc"]
    end
  end

  # No zap stanza required
end
