# This file was generated by GoReleaser. DO NOT EDIT.
cask "kirocc" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "675ff2e2150ed1acfc7bb441452ab6e4ce6dc21b8fbe1c7bdfcaf6acee7b40b2"
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f96b345ef0d4bd8e1c226355bc0e543ef905a3c66ee779dd3db83998d77af93"
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ee331bf1e6deaafb6f974d246131749b71019b186398679c33159e5593a3617"
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2fc690d3c09bf39a9360e6c561b6da494c62abcca54cc48a18c87b5c2ea4c8de"
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kirocc"
  desc "Local proxy server that relays Anthropic Messages API requests to the Kiro backend"
  homepage "https://github.com/d-kuro/kirocc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kirocc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kirocc"]
    end
  end

  # No zap stanza required

end
