# This file was generated by GoReleaser. DO NOT EDIT.
cask "kirocc" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "ef1cbab980de4cd883842265cecf78ebabe883749c1f60716cc0ae3414316822"
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0480c07fa4f524624d434992b835aac763491e754c64f3908703beb89345a589"
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7c8ee992c177d7bc54eb1c0df402f1832c8cda7dcbf7415c8aaad7e60ce55468"
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8bb2f789e8b4bcdfd9e30365ff5bba28fd29aee90e94a998a79898a7f5e4cc31"
      url "https://github.com/d-kuro/kirocc/releases/download/v#{version}/kirocc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kirocc"
  desc "Local proxy server that relays Anthropic Messages API requests to the Kiro backend"
  homepage "https://github.com/d-kuro/kirocc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kirocc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kirocc"]
    end
  end

  # No zap stanza required

end
