# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gwq < Formula
  desc "Git Worktree Manager for efficient worktree operations"
  homepage "https://github.com/d-kuro/gwq"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/d-kuro/gwq/releases/download/v0.1.2/gwq_Darwin_x86_64.tar.gz"
      sha256 "aed66598c9623e0e9bdb842f964595e7d922bb2a9337957637fd0397bd75f177"

      define_method(:install) do
        bin.install "gwq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/d-kuro/gwq/releases/download/v0.1.2/gwq_Darwin_arm64.tar.gz"
      sha256 "feebd322b8eff4365e2f90ad63de6d265a8b6d85793228f6425857a976590ec6"

      define_method(:install) do
        bin.install "gwq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/d-kuro/gwq/releases/download/v0.1.2/gwq_Linux_x86_64.tar.gz"
      sha256 "a689c0cbf0e0bde5304d253df90429c69175893e829c767975706e9f72dc439d"
      define_method(:install) do
        bin.install "gwq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/d-kuro/gwq/releases/download/v0.1.2/gwq_Linux_arm64.tar.gz"
      sha256 "95c52242f1de8b84ba3ac83524a03e9c9316eb62056c35374c04bd5ba513b3dd"
      define_method(:install) do
        bin.install "gwq"
      end
    end
  end

  test do
    system "#{bin}/gwq", "--version"
  end
end
